import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.xml.crypto.Data;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

public class ApplicationCreator extends JDialog {
    private JPanel panelMain;
    private JTextArea textArea;
    private JButton addButton;
    private JRadioButton yellowRadioButton;
    private JRadioButton redRadioButton;
    public MonitoringForm monitoringForm;

    public ApplicationCreator(final String module, final String login) {
        add(panelMain);
        setSize(500, 400);
        setTitle("Monitoring");

        ButtonGroup buttonGroup1 = new ButtonGroup();
        buttonGroup1.add(redRadioButton);
        buttonGroup1.add(yellowRadioButton);


        addButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String status = "На рассмотрении";

                Boolean change;
                if (yellowRadioButton.isSelected()) change = true;
                else change = false;

                String date = new SimpleDateFormat("dd.MM.yyyy").format(Calendar.getInstance().getTime());

                List<String> arguments = new ArrayList<>();
                arguments.add(module);
                arguments.add(login);
                arguments.add(status);
                arguments.add(date);
                arguments.add(String.valueOf(change));
                arguments.add(String.valueOf(3));
                arguments.add(String.valueOf(textArea.getText()));
                ServerQuery.queryPerform(new Message("CreateApplication", arguments));

                monitoringForm.updatingApplicationsTable();


                dispose();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new FormLayout("fill:max(d;155px):grow,left:4dlu:noGrow,fill:172px:grow", "center:d:grow"));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:grow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        CellConstraints cc = new CellConstraints();
        panelMain.add(panel1, cc.xyw(1, 1, 3, CellConstraints.DEFAULT, CellConstraints.FILL));
        textArea = new JTextArea();
        panel1.add(textArea, cc.xyw(1, 3, 9, CellConstraints.FILL, CellConstraints.FILL));
        addButton = new JButton();
        addButton.setText("Добавить заявку");
        panel1.add(addButton, cc.xyw(3, 5, 5));
        final JLabel label1 = new JLabel();
        label1.setText("Замена");
        panel1.add(label1, cc.xy(3, 1));
        yellowRadioButton = new JRadioButton();
        yellowRadioButton.setBackground(new Color(-921344));
        yellowRadioButton.setText("");
        panel1.add(yellowRadioButton, cc.xy(5, 1));
        redRadioButton = new JRadioButton();
        redRadioButton.setBackground(new Color(-981504));
        redRadioButton.setText("");
        panel1.add(redRadioButton, cc.xy(7, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }
}
