import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;

public class AuthForm extends JFrame {
    private JTextField loginField;
    private JButton OKButton;
    private JButton cancelButton;
    private JPasswordField passwordField;
    private JPanel panelMain;
    private JTextField васПриветствуетПрограммаДляTextField;


    public static void main(String args[]) {
    }

    public AuthForm() {
        add(panelMain);
        loginField.setRequestFocusEnabled(true);
        OKButton.setEnabled(false);
        setTitle("Authentication");
        setSize(524, 268);

        loginField.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                changed();
            }

            public void removeUpdate(DocumentEvent e) {
                changed();
            }

            public void insertUpdate(DocumentEvent e) {
                changed();
            }

            public void changed() {
                if (!loginField.getText().equals("") & !passwordField.getText().equals("")) {
                    OKButton.setEnabled(true);
                } else {
                    OKButton.setEnabled(false);
                }

            }
        });

        passwordField.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                changed();
            }

            public void removeUpdate(DocumentEvent e) {
                changed();
            }

            public void insertUpdate(DocumentEvent e) {
                changed();
            }

            public void changed() {
                if (!passwordField.getText().equals("") & !loginField.getText().equals("")) {
                    OKButton.setEnabled(true);
                } else {
                    OKButton.setEnabled(false);
                }

            }
        });

        OKButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                List<String> list = new ArrayList<>();
                list.add(loginField.getText());
                list.add(passwordField.getText());
                Message message = ServerQuery.queryPerform(new Message("CheckAuth", list));
                if (Boolean.valueOf(message.getMessage())) {
                    dispose();
                    Main.openSession(loginField.getText());
                } else {
                    Main.openNotificationForm(String.valueOf(message.getArguments().get(0)));
                    passwordField.setText("");
                }
            }
        });

        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                System.exit(1);
                ServerQuery.quitServer();
            }
        });

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:77px:noGrow,left:4dlu:noGrow,fill:38px:grow,left:4dlu:noGrow,fill:21px:grow,left:4dlu:noGrow,fill:d:noGrow", "center:max(d;88px):noGrow,top:4dlu:noGrow,top:4dlu:noGrow,center:d:grow,top:3dlu:noGrow,center:35px:grow,top:4dlu:noGrow,center:89px:noGrow"));
        loginField = new JTextField();
        loginField.setAutoscrolls(true);
        loginField.setText("");
        CellConstraints cc = new CellConstraints();
        panelMain.add(loginField, cc.xy(7, 4, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label1 = new JLabel();
        label1.setText("Login");
        panelMain.add(label1, cc.xy(5, 4));
        final JLabel label2 = new JLabel();
        label2.setText("Password");
        panelMain.add(label2, cc.xy(5, 6));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panelMain.add(spacer1, cc.xy(9, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        panelMain.add(spacer2, cc.xy(3, 4, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:d:grow", "center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow"));
        panelMain.add(panel1, cc.xyw(3, 8, 7));
        OKButton = new JButton();
        OKButton.setText("OK");
        panel1.add(OKButton, cc.xy(1, 3));
        cancelButton = new JButton();
        cancelButton.setText("Cancel");
        panel1.add(cancelButton, cc.xy(3, 3));
        final com.intellij.uiDesigner.core.Spacer spacer3 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer3, cc.xy(3, 5, CellConstraints.DEFAULT, CellConstraints.FILL));
        passwordField = new JPasswordField();
        panelMain.add(passwordField, cc.xy(7, 6, CellConstraints.FILL, CellConstraints.DEFAULT));
        final com.intellij.uiDesigner.core.Spacer spacer4 = new com.intellij.uiDesigner.core.Spacer();
        panelMain.add(spacer4, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        final com.intellij.uiDesigner.core.Spacer spacer5 = new com.intellij.uiDesigner.core.Spacer();
        panelMain.add(spacer5, cc.xy(11, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        васПриветствуетПрограммаДляTextField = new JTextField();
        васПриветствуетПрограммаДляTextField.setCaretColor(new Color(-2235656));
        васПриветствуетПрограммаДляTextField.setEditable(false);
        васПриветствуетПрограммаДляTextField.setFocusable(false);
        васПриветствуетПрограммаДляTextField.setForeground(new Color(-16777216));
        васПриветствуетПрограммаДляTextField.setRequestFocusEnabled(false);
        васПриветствуетПрограммаДляTextField.setText("Вас приветствует программа для удаленного доступа к контроллерам Mitsubishi Electric");
        panelMain.add(васПриветствуетПрограммаДляTextField, cc.xyw(3, 1, 7, CellConstraints.CENTER, CellConstraints.FILL));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }
}

